<?xml version="1.0"?>
<package format="3">
  <name>ship_gate</name>
  <version>0.1.0</version>
  <description>ShipGate node for ship navigation</description>

  <maintainer email="you@example.com">유민</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geopy</depend>


  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
